In [63]:
import pandas as pd
dfs = pandas.read_html('file:///C:/Users/moc026/Downloads/SaleMonDetail%20(1).html')

In [40]:
df = dfs[0]

In [49]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,2019/06,27.3,26,27.5,25.2,-1.4,-5.11,44.52,+0.09,+6.59,267,+7.56,44.52,+0.09,+6.59,267,+7.56
1,2019/05,25.35,27.4,27.65,24.7,+2.05,+8.09,44.47,+2.58,+4.7,222.5,+7.75,44.47,+2.58,+4.7,222.5,+7.75
2,2019/04,23.8,25.35,25.8,23.7,+1.6,+6.74,43.35,-4.91,+9.24,178.1,+8.54,43.35,-4.91,+9.24,178.1,+8.54
3,2019/03,22.1,23.75,23.75,21.9,+1.65,+7.47,45.6,+16.4,+7.42,134.7,+8.32,45.6,+16.4,+7.42,134.7,+8.32
4,2019/02,21.55,22.1,22.1,21.4,+0.75,+3.51,39.18,-21.5,+11.1,89.11,+8.79,39.18,-21.5,+11.1,89.11,+8.79

In [ ]:
import pandas
customer = pandas.read_csv('https://raw.githubusercontent.com/ywchiu/digiplus_ds/master/data/customer_churn.csv', index_col=0)